site_name: Redes de Computadores - 26.2

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lcarlosazeredo/notas-redes
      name: Repositório no GitHub

theme:
  name: material
  language: pt-BR
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  features:
    - navigation.footer

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - attr_list
  - admonition
  - pymdownx.details
  - toc:
      permalink: false
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js

extra_css:
  - stylesheets/extra.css

nav:
  - Início: index.md
  - Aulas:
    - Aula 01 | 12/08/2026: aulas/Aula01.md
    - Aula 02 | 14/08/2026: aulas/Aula02.md
    - Aula 03 | 19/08/2026: aulas/Aula03.md
    - Aula 04 | 21/08/2026: aulas/Aula04.md
    - Aula 05 | 26/08/2026: aulas/Aula05.md
    - Aula 06 | 28/08/2026: aulas/Aula06.md
    - Aula 07 | 02/09/2026: aulas/Aula07.md
    - Aula 08 | 04/09/2026: aulas/Aula08.md
